apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:4.1
          ports:
            - containerPort: 9042
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - cqlsh -e 'SHOW VERSION' localhost 9042 || exit 1
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - cqlsh -e 'SHOW VERSION' localhost 9042 || exit 1
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 10
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: "flight-cluster"
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
      volumes:
        - name: cassandra-data
          persistentVolumeClaim:
            claimName: cassandra-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard  # descomenta y ajusta según tu cluster
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  ports:
    - port: 9042
      name: cql
  selector:
    app: cassandra
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-init
spec:
  backoffLimit: 5                  # reintenta hasta 5 veces si falla
  template:
    spec:
      restartPolicy: "OnFailure"
      initContainers:
        - name: wait-for-cassandra
          image: busybox:1.28
          command:
            - sh
            - -c
            - |
              echo "Esperando a que Cassandra esté lista..."
              until nc -z cassandra 9042; do
                echo "Cassandra aún no lista, esperando 5s..."
                sleep 5
              done
              echo "Cassandra listo!"
      containers:
        - name: cassandra-init
          image: hineill/ibdn-cassandra-init:latest
          env:
            - name: CASSANDRA_HOST
              value: "cassandra"
            - name: CASSANDRA_PORT
              value: "9042"
          command: ["python", "/app/init.py"]