# k8s/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ibdn

resources:
  # Base
  - base/namespace.yaml
  - base/configmaps.yaml
  - base/secrets.yaml
  - base/infra-pvcs.yaml

  # Infraestructura
  - infra/kafka.yaml
  - infra/cassandra.yaml
  - infra/minio.yaml
  - infra/mlflow.yaml
  # Init jobs
  - init-jobs/cassandra-init.yaml
  - init-jobs/kafka-init.yaml
  - init-jobs/iceberg-init.yaml
  - init-jobs/minio-init.yaml  

  # Spark
  - spark/spark-master.yaml
  - spark/spark-worker.yaml
  # Spark submit

  - spark/spark-train-job.yaml
  - spark/spark-predictor.yaml