FROM apache/spark:4.1.1-scala2.13-java21-python3-r-ubuntu
USER root
COPY resources/spark-pyspark-train-model/requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt
COPY resources/spark-pyspark-train-model/train_spark_mllib_model.py /app/train_spark_mllib_model.py