# k8s/spark/spark-retrain-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: spark-retrain
  namespace: ibdn
spec:
  schedule: "*/20 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
            - name: wait-for-services
              image: busybox:1.28
              command:
                - sh
                - -c
                - |
                  until nc -z spark-master 7077 && nc -z minio 9000 && nc -z mlflow 5000; do
                    echo "waiting for services...";
                    sleep 5;
                  done
          containers:
            - name: spark-train
              image: hineill/ibdn-spark-train-model:latest
              securityContext:
                runAsUser: 0
              envFrom:
                - configMapRef:
                    name: ibdn-config
                - secretRef:
                    name: ibdn-secrets
              command:
                - bash
                - -c
                - |
                  MY_POD_IP=$(hostname -i)
                  /opt/spark/bin/spark-submit \
                    --master spark://spark-master:7077 \
                    --conf spark.driver.bindAddress=0.0.0.0 \
                    --conf spark.driver.host=$MY_POD_IP \
                    --total-executor-cores 4 \
                    --conf spark.cores.max=4 \
                    --executor-memory 1g \
                    --packages org.apache.hadoop:hadoop-aws:3.4.1,org.apache.iceberg:iceberg-spark-runtime-4.0_2.13:1.10.0 \
                    /app/train_spark_mllib_model.py