apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: ibdn
spec:
  type: ClusterIP
  selector:
    app: spark-master
  ports:
    - port: 7077
      name: master
    - port: 8080
      name: webui
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-ui
  namespace: ibdn
spec:
  type: LoadBalancer
  selector:
    app: spark-master
  ports:
    - port: 8080
      name: webui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: ibdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: apache/spark:4.1.1
          securityContext:
            runAsUser: 0
          command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          env:
            - name: SPARK_MASTER_PORT
              value: "7077"