# k8s/base/configmaps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ibdn-config
  namespace: ibdn
data:
  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REQUEST_TOPIC: "flight-delay-ml-request"
  RESPONSE_TOPIC: "flight-delay-ml-response"

  # MinIO
  MINIO_ENDPOINT: "http://minio:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  MLFLOW_S3_ENDPOINT_URL: "http://minio:9000"

  # Rutas de datos y modelos
  TRAINING_DATA_PATH: "s3a://raw/simple_flight_delay_features.jsonl.bz2"
  MODEL_OUTPUT_BASE_PATH: "s3a://models"
  MODEL_BASE_PATH: "s3a://models/production"

  # MLflow
  MLFLOW_TRACKING_URI: "http://mlflow:5000"

  # Spark
  SPARK_MASTER: "spark://spark-master:7077"

  # Flask
  PREDICTION_TOPIC: "flight-delay-ml-request"
  PROJECT_HOME: "/app"