# k8s/base/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ibdn-secrets
  namespace: ibdn
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"